---
- name: install pip dependencies
  pip: name={{item}} state=present
  with_items:
    - pygeoip
    - crypto
    - dpkt
    - pycap
    - ipy

- name: dshell installed?
  stat: path=/home/{{ ansible_ssh_user}}/dshell
  register: dshell

- name: download dshell
  git: repo=https://github.com/USArmyResearchLab/Dshell.git
       dest={{ansible_ssh_user}}
       version=master
  sudo:false
  when: dshell.stat.exists == False

- name: ensure share directory exists
  file: path=/home/{{ ansible_ssh_user }}/dshell/share
        state=directory
        owner={{ ansible_ssh_user }}
        group={{ ansible_ssh_user }}
        mode=700
  #do we need when statement?

- name: check whether GeoIP MaxMind files are installed
  stat: path=/home/{{ ansible_ssh_user }}/dshell/share/GeoIP
  register:geolite

- name:download GeoIP MaxMind data files
  command: wget {{item}}
  with_items:
  - http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz
  - http://download.maxmind.com/download/geoip/database/asnum/GeoIPASNumv6.dat.gz
  - http://download.maxmind.com/download/geoip/database/asnum/GeoIPASNum.dat.gz
  - http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
  - http://geolite.maxmind.com/download/geoip/database/GeoIPv6.dat.gz
  when:geolite.stat.exists == False

- name: extract tarball
  command: tar -xzvf {{item}}
  with_items:
  - http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz
  - http://download.maxmind.com/download/geoip/database/asnum/GeoIPASNumv6.dat.gz
  - http://download.maxmind.com/download/geoip/database/asnum/GeoIPASNum.dat.gz
  - http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
  - http://geolite.maxmind.com/download/geoip/database/GeoIPv6.dat.gz
  when:geolite.stat.exists == False

- name: move files to correct location
  command: mv {{item}} /home/{{ ansible_ssh_user }}/dshell/share/GeoIP
  with_items:
  - GeoIP.dat
  - GeoIPv6.dat
  - GeoIPASNum.dat
  - GeoIPASNumv6.dat
  when: geolite.stat.exists == False

- name: make
  command: "make"
  when:geolite.stat.exists == False
