---
- name: install pip dependencies
  pip: name={{item}} state=present
  with_items:
    - pygeoip
    - crypto
    - dpkt
    - pycap
    - ipy

- name: dshell installed?
  stat: path=/home/{{ansible_ssh_user}}/Dshell
  register: dshell

- name: download dshell
  git: repo=https://github.com/USArmyResearchLab/Dshell.git
       dest=/home/{{ ansible_ssh_user }}/Dshell
       accept_hostkey=True
  when: dshell.stat.exists == False

- name: ensure share directory exists
  file: path=/home/{{ ansible_ssh_user }}/Dshell/share/GeoIP
        state=directory

- name: check whether GeoIP MaxMind files are installed
  stat: path=/home/{{ansible_ssh_user}}/Dshell/share/GeoIP/GeoLiteCity.dat
  register: geolite

- name: download GeoIP MaxMind data files
  get_url: url={{item}} dest=/home/{{ansible_ssh_user}}/Dshell/share/GeoIP/
  with_items:
  - http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz
  - http://download.maxmind.com/download/geoip/database/asnum/GeoIPASNumv6.dat.gz
  - http://download.maxmind.com/download/geoip/database/asnum/GeoIPASNum.dat.gz
  - http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
  - http://geolite.maxmind.com/download/geoip/database/GeoIPv6.dat.gz
  when: geolite.stat.exists == False

- name: extract tarball
  command: gunzip /home/{{ansible_ssh_user}}/Dshell/share/GeoIP/{{ item }}
  with_items:
  - GeoIP.dat.gz
  - GeoIPASNumv6.dat.gz
  - GeoIPASNum.dat.gz
  - GeoLiteCity.dat.gz
  - GeoIPv6.dat.gz
  when: geolite.stat.exists == False

- name: make
  shell: true && {{ item }} chdir=/home/{{ansible_ssh_user}}/Dshell
  with_items:
    - make
  when: geolite.stat.exists == False
