---
- name: install apt dependencies
  apt: name={{item}} state=present
  with_items:
    - python-crypto
    - python-dpkt
    - python-ipy
    - python-pypcap

- name: install pip dependencies
  pip: name={{item}} state=present
  with_items:
    - pygeoip
